apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    freaks.service: postservice
  name: postservice
  namespace: freaks
spec:
  replicas: 1
  selector:
    matchLabels:
      freaks.service: postservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        freaks.service: postservice
    spec:
      containers:
      - image: 85116875693/freaks-postservice:latest
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ASPNETCORE_URLS
          value: http://+:80 
        name: postservice
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "100m"
      hostname: postservice
      restartPolicy: Always