apiVersion: v1
kind: Service
metadata:
  labels:
    freaks.service: postservice-db
  name: postservice-db
  namespace: freaks
spec:
  type: ClusterIP
  ports:
  - name: "http"
    protocol: TCP
    port: 3308
    targetPort: 3308
  selector:
    freaks.service: postservice-db
status:
  loadBalancer: {}