apiVersion: v1
kind: Service
metadata:
  labels:
    freaks.service: freaksgateway
  name: freaksgateway
  namespace: freaks
spec:
  type: ClusterIP
  ports:
  - name: "http"
    port: 6007
    targetPort: 80
  - name: "https"
    port: 6008
    targetPort: 443
  selector:
    freaks.service: freaksgateway
status:
  loadBalancer: {}