apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    freaks.service: userservice
  name: userservice
  namespace: freaks
spec:
  replicas: 1
  selector:
    matchLabels:
      freaks.service: userservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        freaks.service: userservice
    spec:
      containers:
      - image: 85116875693/freaks-userservice:latest
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ASPNETCORE_URLS
          value: http://+:80 
        name: userservice
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "100m"
      hostname: userservice
      restartPolicy: Always