apiVersion: v1
kind: Service
metadata:
  labels:
    freaks.service: userservice
  name: userservice
  namespace: freaks
spec:
  type: ClusterIP
  ports:
  - name: "http"
    port: 6005
    targetPort: 80
  - name: "https"
    port: 6006
    targetPort: 443
  selector:
    freaks.service: userservice
status:
  loadBalancer: {}