apiVersion: v1
kind: Service
metadata:
  labels:
    freaks.service: userservice-db
  name: userservice-db
  namespace: freaks
spec:
  type: ClusterIP
  ports:
  - name: "http"
    protocol: TCP
    port: 3307
    targetPort: 3307
  selector:
    freaks.service: userservice-db
status:
  loadBalancer: {}