apiVersion: v1
kind: Service
metadata:
  labels:
    freaks.service: freaksfrontend
  name: freaksfrontend
  namespace: freaks
spec:
  type: ClusterIP
  ports:
  - name: "http"
    port: 4200
    targetPort: 4200
  selector:
    freaks.service: freaksfrontend
status:
  loadBalancer: {}