apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    freaks.service: freaksfrontend
  name: freaksfrontend
  namespace: freaks
spec:
  replicas: 1
  selector:
    matchLabels:
      freaks.service: freaksfrontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        freaks.service: freaksfrontend
    spec:
      containers:
      - image: 85116875693/freaks-frontend:latest
        imagePullPolicy: Always
        name: freaks-frontendservice
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "100m"
      hostname: freaksfrontend
      restartPolicy: Always
status: {}