apiVersion: v1
kind: Service
metadata:
  labels:
    freaks.service: services-db
  name: services-db
  namespace: freaks
spec:
  type: ClusterIP
  ports:
  - name: "http"
    protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    freaks.service: services-db
status:
  loadBalancer: {}