apiVersion: v1
kind: Service
metadata:
  labels:
    freaks.service: authservice
  name: authservice
  namespace: freaks
spec:
  type: ClusterIP
  ports:
  - name: "http"
    port: 6001
    targetPort: 80
  - name: "https"
    port: 6002
    targetPort: 443
  selector:
    freaks.service: authservice
status:
  loadBalancer: {}