apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authservice-db-data
  namespace: freaks
spec:
  storageClassName: microk8s-hostpath
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}