apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    freaks.service: freaksgateway
  name: freaksgateway
  namespace: freaks
spec:
  replicas: 1
  selector:
    matchLabels:
      freaks.service: freaksgateway
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        freaks.service: freaksgateway
    spec:
      containers:
      - image: 85116875693/freaks-apigateway:latest
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ASPNETCORE_URLS
          value: http://+:80
        name: freaks-apigateway
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "100m"
      hostname: freaksgateway
      restartPolicy: Always
status: {}